### PR TITLE
Add support for cyphersystem currencies

### PR DESCRIPTION
**Pull request by jparks**

### CODE REVIEW

**Comment by ironmonk88** [comment]
Thank you very much for the code!

Changes have been made, but I'm rejecting this only because I had to correct a couple of things.  And therefore this patch would conflict with the result.
```
let currency = MonksEnhancedJournal.currencies.find(c => c.id == denomination);
                    let systemcoins = {
                        name6: i18n('CYPHERSYSTEM.Adamantine'),
                        name5: i18n('CYPHERSYSTEM.Mithral'),
                        name4: i18n('CYPHERSYSTEM.Platinum'),
                        name3: i18n('CYPHERSYSTEM.Gold'),
                        name2: i18n('CYPHERSYSTEM.Silver'),
                        name: i18n('CYPHERSYSTEM.Copper')
                    };

                    let coins = actor.data.data.settings.currency;

                    let coinname = Object.keys(coins).find(key => coins[key] == currency.name) || Object.keys(systemcoins).find(key => systemcoins[key] == currency.name);
                    if (!coinname)
                        return 0;

                    let qtyname = coinname.replace("name", "quantity");

                    coinage = parseInt(coins[qtyname] || 0);
```
If the currency name was the default system name then it wouldn't be able to find the coin because the names in the actor data are all blank.
And you don't need to use a mapping object, you can just replace `name` with `quantity` to find the correct value.
And added some error checking in case the coin wasn't found.

Also the styling needs to only be applied to the cypher system, not every system.  And there were a couple of other ones that needed to be fixed as well.

Changes should go through in the next patch.  Which hopefully will be some time this weekend.

Thank you again.

**Comment by jparks** [comment]
Those names are just placeholders and are user settable. For instance if there is only once currency active then the default name is set to CYPHERSYSTEM.Shins rather than CYPHERSYSTEM.Copper. 

```
<input class="auto-margin" 
  name="data.settings.currency.name" type="text" 
  value="{{data.settings.currency.name}}" data-dtype="String" 
  placeholder="{{#if (eq data.settings.currency.howMany '1')}}{{localize 'CYPHERSYSTEM.Shins'}}{{else}}{{localize 'CYPHERSYSTEM.Copper'}}{{/if}}">
```

The names and number of currencies are meant to be flexible depending on the setting. Without the mapping only the default names would work.

**Comment by ironmonk88** [comment]
But good catch on the Shins.  I didn't scroll down far enough to see that "copper" could be two things.
I think changing it to 
```
let coins = actor.data.data.settings.currency;
                    let systemcoins = {
                        name6: i18n('CYPHERSYSTEM.Adamantine'),
                        name5: i18n('CYPHERSYSTEM.Mithral'),
                        name4: i18n('CYPHERSYSTEM.Platinum'),
                        name3: i18n('CYPHERSYSTEM.Gold'),
                        name2: i18n('CYPHERSYSTEM.Silver'),
                        name: (coins.howMany == '1' ? i18n('CYPHERSYSTEM.Shins') : i18n('CYPHERSYSTEM.Copper'))
                    };
```
Should catch the alternate default.

**Comment by ironmonk88** [comment]
Closing this as the code was added, just couldn't be merged.
Thank you again.

**Pull request closed without merging**
